test

diff --git a/.github/workflows/check-labels.yml b/.github/workflows/check-labels.yml
--- a/.github/workflows/check-labels.yml
+++ b/.github/workflows/check-labels.yml
@@ -6,27 +6,31 @@ on:
 
 jobs:
   check-disallowed-labels:
+    if: contains(github.event.pull_request.labels.*.name, 'draft')
     runs-on: ubuntu-22.04
     steps:
       - name: Check for disallowed labels
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const disallowedLabels = ['Draft', 'Duplicated', 'Do not merge'];
-            
-            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number
-            });
-            
-            console.log(labels);
-            
-            const foundDisallowedLabels = labels
-              .filter((label) => disallowedLabels.includes(label.name))
-              .map((label) => label.name)
-            
-            if (foundDisallowedLabels.length > 0) {
-              core.setFailed(`This pull request has the following disallowed label and cannot be merged: ${foundDisallowedLabels.join(', ')}`)
-            }
+        run: |
+          echo "This pull request has the following disallowed label and cannot be merged"
+          exit 1
+#        uses: actions/github-script@v6
+#        with:
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#          script: |
+#            const disallowedLabels = ['Draft', 'Duplicated', 'Do not merge'];
+#
+#            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              issue_number: context.issue.number
+#            });
+#
+#            console.log(labels);
+#
+#            const foundDisallowedLabels = labels
+#              .filter((label) => disallowedLabels.includes(label.name))
+#              .map((label) => label.name)
+#
+#            if (foundDisallowedLabels.length > 0) {
+#              core.setFailed(`This pull request has the following disallowed label and cannot be merged: ${foundDisallowedLabels.join(', ')}`)
+#            }
